name: Deploy job - common

on:
  release:
    types: [published]

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: yarn install
      - name: Build common
        run: yarn build:common
      - name: cd to main directory
        run: cd ./packages/main
      - name: Build docs
        run: yarn build --if-present
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.TEST_COV_WEB_MAIN_FTP_SERVER }}
          username: ${{ secrets.TEST_COV_WEB_MAIN_FTP_ACCOUNT }}
          password: ${{ secrets.TEST_COV_WEB_MAIN_FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./
